# Generated by Django 5.1.4 on 2025-02-09 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='genre',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='genres',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='newsarticle',
            table='news_articles',
        ),
    ]
