# Generated by Django 5.1.4 on 2025-02-15 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsarticle_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='user_id',
            new_name='app_id',
        ),
        migrations.CreateModel(
            name='NewsSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('genres_selected', models.JSONField(default=list)),
                ('published_at', models.DateField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_summary',
                'unique_together': {('app_id', 'published_at')},
            },
        ),
    ]
