# Generated by Django 5.1.4 on 2025-02-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_user_id_newsarticle_app_id_newssummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='bias_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='credibility_score',
            field=models.FloatField(default=0.5),
        ),
    ]
